URL=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

Browser=chrome

Incognito=true

Headless=false

ExtentReport=false

SaveSuccessScreenshot=false

SaveFailureScreenshot=false

SaveSkippedScreenshot=false
